day3/devops/books/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [

]

day3/devops/devops/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include('hello.urls')),
    path('books/',include('books.urls')),
]

day3/devops/hello/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from hello import views
from . import views
from . import views
app_name = 'hello'
urlpatterns = [
 #path('index/',IndexView.as_view(),name='index'),
 #path('index.html', views.index, name='index'),
 path('useradd/', views.UserAddView.as_view(),name='useradd'),
 path('userlist/', views.UserListView.as_view(), name='userlist'),
 re_path(r'usermodify/(?P<pk>[0-9]+?)/', views.UserModifyView.as_view(), name='usermodify'),
 re_path(r'userdel/(?P<pk>[0-9]+?)/', views.UserDelView.as_view(), name='userdel'),
re_path(r'userdetail/(?P<pk>[0-9]+?)/', views.UserDetailView.as_view(), name='userdetail'),


]
# urlpatterns = [
#     # 2.1: 普通传参url基本和⽆参数⼀样
#     path('', views.index, name='index'),
#     # you can also use regular expressions. To do so, use re_path()instead of path().正则⽤re_path
#     # URL中每个位置数值和view中定义的参数顺序⼀⼀对应（代码可读性不好，不推荐）
#     # 2.2：位置匹配
#     #re_path('([0-9]{4})/([0-9]{2})/', views.index, name='index'),
#     # 2.3：关键字匹配(最优雅) (?<参数名>参数类型)??视图中直接通过参数名获取值（最常⽤）
#
# ]

day3/devops/hello/models.py
from django.db import models


# Create your models here.

class User(models.Model):
    SEX = (
        (0, '男'),
        (1, '女'),
    )
    name = models.CharField(max_length=20, help_text="用户名")
    password = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    sex = models.IntegerField(choices=SEX, null=True, blank=True)

    # def __str__(self):
    #     return self.name, self.sex

day3/devops/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse, QueryDict
import time, datetime
from django.contrib import messages
from hello.models import User
from django.shortcuts import reverse
from django.views.generic import View
from django.views.generic import TemplateView
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin


class UserAddView(SuccessMessageMixin, CreateView):
    model = User
    fields = ('name', 'password', 'sex','age')
    success_message = "%(name)s was created successfully"

    def get_success_url(self):
        print(self.request.POST)
        if '_addanother' in self.request.POST:
            return reverse('hello:useradd')
        return reverse('hello:userlist')


class UserDetailView(SuccessMessageMixin, DetailView):
    template_name = "hello/user_detail.html"
    # 同价 object = User.objects.get(pk=pk)
    model = User
    # 自定义传给前端模板渲染的变量，默认object
    context_object_name = "user"


class UserDelView(SuccessMessageMixin, DeleteView):
    """
    删除用户
    """
    # 默认模版 hello/user_confirm_delete.html #
    template_name = 'hello/user_confirm_delete.html'
    model = User

    def get_success_url(self):
        return reverse('hello:userlist')


class UserListView(ListView):
    """
    用户列表，最经典的用法，列表+搜索+上下文
     """
    template_name = "hello/user_list.html"
    model = User
    # object_list = User.objects.all() model = User
    # 自定义传给前端模板渲染的变量，默认object_list
    context_object_name = "users"
    keyword = ""

    # 数据过滤
    def get_queryset(self):
        queryset = super(UserListView, self).get_queryset()
        self.keyword = self.request.GET.get("keyword", "")
        if self.keyword:
            queryset = queryset.filter(name=self.keyword)
            #queryset = queryset.filter(name__icontains=self.keyword)

        return queryset

    # 需要传给前端的数据大字典
    # def get_context_data(self, **kwargs):
    #     context = super(UserListView, self).get_context_data(**kwargs)
    #     context['keyword'] = self.keyword
    #     return context


class UserModifyView(SuccessMessageMixin, UpdateView):
    """
    更新用户
    """
    template_name = "hello/user_edit.html"
    model = User
    fields = ('name', 'password', 'sex','age')
    success_message = "%(name)s was update successfully"

    def get_success_url(self):
        if '_continue' in self.request.POST:
            return reverse('hello:usermodify', kwargs={'pk': self.object.pk})
        return reverse('hello:userlist')

# # 添加用户
# def useradd(request):
#     messages = {}
#     if request.method == 'GET':
#         return render(request, 'hello/useradd.html')
#     else:
#         user = request.POST.get('user')
#         password = request.POST.get('password')
#         password2 = request.POST.get('password2')
#         sex = request.POST.get('gender')
#         age = request.POST.get('age')
#         # 两次密码输入校验
#         if password != password2:
#             messages = {"code":1,"error":"两次输入密码不匹配"}
#             return render(request, 'hello/useradd.html',{"msg": messages})
#         try:
#             users = User.objects.get(name=user)
#             messages = {"code": 1, "error": "用户已经存在"}
#             return render(request, 'hello/useradd.html', {"msg": messages})
#         except User.DoesNotExist:
#             data = {'name': user, 'password': password, 'sex': sex, 'age': age}
#             User.objects.create(**data)
#             messages = {"code": 0, "result": "用户添加成功"}
#         return render(request, 'hello/useradd.html',{"msg": messages})
#
#
# def userlist(request):
#     # 默认显示前5条
#     if request.method == 'GET':
#         users = User.objects.filter().values('id','name', 'sex', 'age').order_by('name')[:5]
#         return render(request, 'hello/userlist.html', {"users": users})
#     else:
#         # 根据用户名搜索
#         if 'search' in request.POST:
#             username = request.POST.get('user',"")
#             try:
#                 users = User.objects.get(name=username)
#             except User.DoesNotExist:
#                 messages.error(request, '没有找到用户')
#                 users = list()
#             users = User.objects.filter(name=username)
#             return render(request, 'hello/userlist.html', {"users": users})
#             # return HttpResponse("%s is delete" % (username))
#         # 表单“更新”功能（根据id
#
# def userdel(request,**kwargs):
#     #return HttpResponse("year is %s" % (kwargs))
#     userid = kwargs.get('pk')
#     if request.method == 'POST':
#         User.objects.filter(id=userid).delete()
#         #return HttpResponse("%s is delete" % (userid))
#         messages = {"code": 1, "error": "删除成功"}
#         # #return HttpResponse("data is %s  keyword %s" % (data,kwargs))
#         #users = User.objects.filter().values('name', 'age').order_by('name')[:5]
#         return render(request, 'hello/userdel.html',{"msg": messages})
#     else:
#         users = User.objects.filter(id=userid).values('name')
#         #return HttpResponse("res is %s %s" % (users[0]['name'],users[0]['age']))
#         return render(request, 'hello/userdel.html', {"users": users})
#
# def usermodify(request,**kwargs):
#     #return HttpResponse("year is %s" % (kwargs))
#     userid = kwargs.get('pk')
#     if request.method == 'POST':
#         # return HttpResponse("year is %s" % (request.POST.get('name')))
#         # data=request.POST.dict()
#         #return HttpResponse("data is %s  keyword %s" % (data,kwargs))
#         # user = User()
#         data = {"name": request.POST.get('name'), "age":request.POST.get('age'),
#                 "sex": request.POST.get('gender'), "password": request.POST.get('password')}
#         User.objects.filter(id=userid).update(**data)
#         messages = {"code": 1, "error": "更新成功"}
#         #return HttpResponse("data is %s  keyword %s" % (data,kwargs))
#         #User.objects.filter(id=userid).update(**data)
#         return render(request, 'hello/usermodify.html', {"msg": messages})
#     else:
#         users = User.objects.filter(id=userid).values('id', 'name', 'sex', 'age','password')
#         #return HttpResponse("res is %s %s" % (users[0]['name'],users[0]['age']))
#         return render(request, 'hello/usermodify.html', {"users": users})

day3/devops/templates/hello/user_confirm_delete.html
<!‐‐ 继承母版不变的部分 ‐‐>
{% extends "base.html" %}
<!‐‐ 重写母版变的部分‐‐>
{% block title %} 用户删除 {% endblock %}
<!‐‐ 重写母版变的部分‐‐> {% block content %}
<form action="" method="post">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="确定" />
</form>
{% endblock %}

day3/devops/templates/hello/user_detail.html
<!‐‐ 继承母版不变的部分 ‐‐>
{% extends "base.html" %}
<!‐‐ 重写母版变的部分‐‐>
{% block title %} 个人信息 {% endblock %}
<!‐‐ 重写母版变的部分‐‐> {% block content %}
<p> 姓名： {{ user.name }} </p>
<p> 密码： {{ user.password }}</p>
<p> 年龄： {{ user.age }}</p>
<p> 性别： {{ user.sex }}</p>
{% endblock %}

day3/devops/templates/hello/user_edit.html
{% extends "base.html" %}
<!‐‐ 重写母版变的部分‐‐>
{% block title %} 更新用户 {% endblock %}
<!‐‐ 重写母版变的部分‐‐>
{% block content %}
{% if form %}
<p style="color:red"> {{ form.errors}} </p>
{% endif %}
{% if messages %}
<ul>{% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }} </li>
    {% endfor %}
</ul> {% endif %}
<form method="post" action="" >
    姓名: <input type="text" name="name" value={{ user.name }}> <br> <br>
    密码: <input type="password" name="password" value={{ user.password }}> <br> <br>
    年龄: <input type="text" name="age" value={{ user.age }}> <br> <br>
    性别: <input type="radio" name="sex" value="0"
               {% if object %}
               {% if object.sex == 0 %} checked {% endif %} {% endif %} >
    男 <input type="radio" name="sex" value="1" {% if object %} {% if object.sex == 1 %} checked {% endif %} {% else %}checked {% endif %}
   >女 <br> <br>
    <input type="submit" value="保存" name="_save">
    <input type="submit" value="保存并继续编辑" name="_continue">
</form>
{% endblock %}

day3/devops/templates/hello/user_form.html
{% extends "base.html" %}
<!‐‐ 重写母版变的部分‐‐>
{% block title %} 创建用户 {% endblock %}
<!‐‐ 重写母版变的部分‐‐>
{% block content %}
{% if form %}
    <p style="color:red"> {{ form.errors }} </p>
{% endif %}
{% if messages %}
    <ul>{% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"
            {% endif %}> {{ message }} </li>
        {% endfor %} </ul>
{% endif %}
<form method="post" action="" >
    姓名: <input type="text" name="name" >
    {% if form.name %}
         <p style="color:red"> {{ form.name.errors}} </p>
    {% endif %} <br>
    密码: <input type="password" name="password">
    {% if form.password %} <p style="color:red"> {{ form.password.errors}} </p>
    {% endif %} <br>
    年龄: <input type="text" name="age" > <br>
    性别:
    <input type="radio" name="sex" value="0" checked>男
    <input type="radio" name="sex" value="1">女 <br>
    <input type="submit" value="保存" name="_save">
    <input type="submit" value="保存并增加另一个" name="_addanother">
</form>
{% endblock %}

day3/devops/templates/hello/user_list.html
<!‐‐ 继承母版不变的部分 ‐‐>
{% extends "base.html" %}
<!‐‐ 重写母版变的部分‐‐>
{% block title %} 用户列表 {% endblock %}
<!‐‐ 重写母版变的部分‐‐>
{% block content %}
<!‐‐ 搜索框 ‐‐>
<form action="{% url 'hello:userlist' %}">
    <input type="text" name="keyword" value="{{ keyword }}"><button type="submit">搜索</button>
<form>
<!‐‐ 数据表格 ‐‐>
    <table border="1">
        <thead>
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>密码</th>
            <th>年龄</th>
            <th>性别</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.password }}</td>
            <td>{{ user.age }}</td>
            <td>
                {% if user.sex == 0 %} 男 {% elif user.sex == 1 %}女 {% else %} 未定义 {% endif %} </td>
            <td>
                <a href="{% url 'hello:usermodify' user.id %}">更新</a>
                <a href="{% url 'hello:userdel' user.id %}">删除</a>
                 <a href="{% url 'hello:userdetail' user.id %}">详细</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endblock %}

day3/devops/templates/hello/useradd.html
{% extends "base.html" %}
<p> {% block tile %} 用户添加 {% endblock %} </p>

{% block content %}
{% if msg.code == 0 %}
<p style="color:green"> {{msg.result}} </p>
{% else %}
<p style="color:red"> {{msg.error}} </p>
{% endif%}
    <form action="" method="post">

      用户名: <input type="text" name="user"><br>
      输入密码: <input type="password" name="password"><br>
      再次输入: <input type="password" name="password2"><br>
        年龄: <input type="text" name="age"><br>
      性别: <input type="radio" name="gender" value="0" checked>男

      <input type="radio" name="gender" value="1">女 <br>

      <input type="submit" value="提交">
    </form>
{% endblock %}

day3/devops/templates/hello/userdel.html
{% extends "base.html" %}
<p> {% block tile %} 用户删除 {% endblock %} </p>
{% block content %}
{% if msg.code == 0 %}
<p style="color:green"> {{msg.result}} </p>
{% else %}
<p style="color:red"> {{msg.error}} </p>
{% endif%}
{% for user in users %}
<form action="" method="post">
<h2>是否删除用 {{ user.name }} ?</h2>
    <button type="submit">删除</button>
    <button><a href="{% url 'hello:userlist' %}">取消</a></button>
</form>
{% endfor %}

{% endblock %}

day3/devops/templates/hello/userlist.html
{% extends "base.html" %}
<p> {% block tile %} 用户列表 {% endblock %} </p>
{% block content %}
{% if msg.code == 0 %}
<p style="color:green"> {{msg.result}} </p>
{% else %}
<p style="color:red"> {{msg.error}} </p>
{% endif%}
<form action="" method="post">
      用户名: <input type="text" name="user">  <input type="submit" value="搜索" name="search">
</form>
<table border="1">
    <tr>
        <td>id</td>
        <td>姓名</td>
        <td>性别</td>
        <td>年龄</td>
        <td>操作</td>
    </tr>
{% for user in users %}
   <form action="" method="post">
       <tr >
           <td>{{user.id}}</td>
        <td>{{user.name}}</td>
           <td>  {% if  user.sex  == 0 %} 男 {% else %} 女 {% endif %} </td>
           <td> {{user.age}} </td>
         <td>
             <a href="{% url 'hello:modify' user.id %} ">更新</a>
             <a href="{% url 'hello:userdel' user.id %} ">删除</a>

         </td>
    </tr>
     </form>
    {% endfor %}
</table>
{% endblock %}

day3/devops/templates/hello/usermodify.html
{% extends "base.html" %}
<p> {% block tile %} 更新 {% endblock %} </p>
{% block content %}
{% if msg.code == 0 %}
<p style="color:green"> {{msg.result}} </p>
{% else %}
<p style="color:red"> {{msg.error}} </p>
{% endif%}
{% for user in users %}
<form action="" method="post">
      用户名: <input readonly="true" type="text" name="name" value={{user.name}}><br><br>
      密码: <input name="password" value={{user.password}}><br><br>
      年龄:  <input type="text" name="age" value={{user.age}}><br><br>
        {% if user.sex == 1 %}
      性别: <input type="radio" name="gender" value="0" checked>男
      <input type="radio" name="gender" value="1">女 <br>
       {%  else %}
         性别: <input type="radio" name="gender" value="0">男
      <input type="radio" name="gender" value="1" checked>女 <br>
        {% endif %}
      <input type="submit" value="更新" name="update">
      <input type="submit" value="取消" name="cancel">
    </form>
    {% endfor %}
{% endblock %}